spring:
  data:
    mongodb:
      uri: mongodb+srv://maxvpire:max26156@cluster0.e6kkugm.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: appointments
      authentication-database: admin

server:
  port: 7755
