spring:
  data:
    mongodb:
      uri: mongodb://mongo:27017/appointments  # Use service name
      host: mongo                       # Or use host property
      port: 27017
      username: root
      password: example
      database: yourdb
      database: appointments
      authentication-database: admin

server:
  port: 7755
