# spring:
#   cloud:
#     gateway:
#       routes:

#         - id: patients-service
#           uri: http://localhost:8081
#           predicates:
#             - Path=/api/v1/patient/**

#         - id: doctors-service
#           uri: http://localhost:7799
#           predicates:
#             - Path=/api/v1/doctor/**

#         - id: administration-service
#           uri: http://localhost:7744
#           predicates:
#             - Path=/api/v1/administrations/**

#         - id: appointments-service
#           uri: http://localhost:7755
#           predicates:
#             - Path=/api/v1/appointment/**

#         - id: medicalrecords-service
#           uri: http://localhost:7766
#           predicates:
#             - Path=/api/v1/medication/records/**
#             - Path=/api/v1/prescriptions/**

#         - id: payment-service
#           uri: http://localhost:7711
#           predicates:
#             - Path=/api/v1/payment/**
#             - Path=/api/v1/invoices/**

#         - id: rates-service
#           uri: http://localhost:7733
#           predicates:
#             - Path=/api/v1/rates/**

#         - id: users-service
#           uri: http://localhost:7722
#           predicates:
#             - Path=/api/v1/users/**

# server:
#   port: 7707


spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Enable service discovery
          lower-case-service-id: true
      routes:
        - id: patients-service
          uri: lb://patients-service  # Use load balancer + service name
          predicates:
            - Path=/api/v1/patient/**
          filters:
            - StripPrefix=1

        - id: doctors-service
          uri: lb://doctors-service
          predicates:
            - Path=/api/v1/doctor/**
          filters:
            - StripPrefix=1

        - id: administration-service
          uri: lb://administration-service
          predicates:
            - Path=/api/v1/administrations/**
          filters:
            - StripPrefix=1

        - id: appointments-service
          uri: lb://appointments-service
          predicates:
            - Path=/api/v1/appointment/**
          filters:
            - StripPrefix=1

        - id: medicalrecords-service
          uri: lb://medicalrecords-service
          predicates:
            - Path=/api/v1/medication/records/**
            - Path=/api/v1/prescriptions/**
          filters:
            - StripPrefix=1

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/payment/**
            - Path=/api/v1/invoices/**
          filters:
            - StripPrefix=1

        - id: rates-service
          uri: lb://rates-service
          predicates:
            - Path=/api/v1/rates/**
          filters:
            - StripPrefix=1

        - id: users-service
          uri: lb://users-service
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=1

server:
  port: 7707

eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/
  instance:
    prefer-ip-address: true