spring:
  data:
    mongodb:
      uri: mongodb://mongo:27017/patients  # Use service name
      host: mongo                       # Or use host property
      port: 27017
      username: root
      password: example
      database: patients
      authentication-database: admin


server:
  port: 7788

